language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly
    - hhvm

matrix:
    include:
        - COMPOSER_PREFER_LOWEST=
        - COMPOSER_PREFER_LOWEST=1

install:
    - composer self-update
    - if [[ ! $COMPOSER_PREFER_LOWEST ]]; then composer install --no-interaction --prefer-source; fi
    - if [[ $COMPOSER_PREFER_LOWEST ]]; then composer update --no-interaction --prefer-source --prefer-lowest --prefer-stable; fi

script: composer test
